### ISSUE TITLE
Time out

### ISSUE THREAD

**Issue by AzazelHD** [arrrlo/Google-Images-Search#109]
Hi, sometimes i get this error ``requests.exceptions.ConnectionError: HTTPConnectionPool(host='mythirion.co.uk', port=80): Max retries exceeded with url:``

And whole script crashes. How can I avoid it?

**Comment by arrrlo** [comment]
Hi @AzazelHD,

The simplest way to tackle this problem is to try - except `gis.search(...)` part in your script:
```python
import requests

try:
    gis.search(...)
except requests.exceptions.ConnectionError:
    pass
```

With this quick solution your script will fetch only images from the first one till the one before the exception. The rest will be ignored because whole images fetching crashed but not your script.
This should be done directly in package so only problematic image url should be ignored.

Thanks!
Ivan.
