### ISSUE TITLE
UnknownApiNameOrVersion: name: customsearch  version: v1

### ISSUE THREAD

**Issue by AIManifest** [arrrlo/Google-Images-Search#156]
`nextcord.errors.ApplicationInvokeError: Command raised an exception: UnknownApiNameOrVersion: name: customsearch  version: v1`

Is this an issue on Google's end? Any help would be appreciated. Thanks in advance for your time.

**Comment by arrrlo** [comment]
Looks like sometimes Google API has problems with API discovery doc:
https://github.com/googleworkspace/python-samples/issues/194
https://stackoverflow.com/questions/66700249/google-gmail-api-works-fine-as-py-but-throws-googleapiclient-errors-unknownap

This could be due to the google's dependency libs or something else.
Try to play with `cache_discovery` argument when conducting the search:
```python
gis = GoogleImagesSearch(GOOGLE_API_KEY, CXID)
_search_params = {...}
gis.search(search_params=_search_params, cache_discovery=True)
# the default is False
```
