### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by LNR-lifenr** [arrrlo/Google-Images-Search#81]
Hi

Does this code allow me to get the image url and the original url of the site the image is from to allow attribution.

Thanks

**Comment by arrrlo** [comment]
Hi,

unfortunately, this lib doesn't fetch origin site URL.
But this is a good idea.
Let me check if that is possible.

**Comment by LNR-lifenr** [comment]
That would be great if it could.

Thanks for the reply

**Comment by TomasOdio2003** [comment]
Has this been implemented? I noticed that when I run it using the CLI usage it does return the image link but I cant find anyway to get it with Programmatic usage

**Comment by kraftydevil** [comment]
> Hi,
> 
> unfortunately, this lib doesn't fetch origin site URL.
> But this is a good idea.
> Let me check if that is possible.

Any word on this? I'd like to second the request.

If I had the image URL(s), I could then use this library with other image APIs that require an image URL and unfortunately don't allow lookup by an actual image.

My particular use case is to use the URLs in a reverse image search API, with the intention of finding higher resolutions of each image.

Example:
- Do an image search with Google-Images-Search
- Grab X images and their corresponding image URLs.
- View the X images and select the ones I want to keep.
- For each kept image URL, do a reverse image search, looking for matching images with higher resolutions.

Reverse image search API: https://github.com/vivithemage/mrisa.

**Interface changes**
Some kind of output mode that returns 'just URLs' or both (images and URLs). Your examples currently have 'just search' and 'search and download', so maybe search would just always return image URLs and search+download would yield both? 

If there's multiple image URLs available per image (image url + original site image url), then maybe a more complex output like json output is warranted.

**Current Possible Workaround**
Without this feature, I'd have to upload the images that Google-Images-Search finds to an image hosting site, which will increase execution time per image and probably cost me actual $. 

This seems unnecessary since Google-Images-Search probably knows the URLs because that's how it's downloading them, right?

**Comment by MrKelpy** [comment]
Any update on this?

**Comment by arrrlo** [comment]
Hi guys, happy to inform you this is implemented now.
New version is live: 1.4.0
To know how to use it, read this:
https://github.com/arrrlo/Google-Images-Search#programmatic-usage
